### ISSUE TITLE
Sequenzdiagramm: Verbindungsinitialisierung, Spielstart

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/Meilensteine#10]

**Comment by ottojo** [comment]
@Marco5de Please Review, für mich sieht das gut genug aus

**Comment by Marco5de** [comment]
Sollte definitiv genug sein, um einen Überblick zu bekommen. Sollte sich da durch den Standard nochmal was ändern, kann man das ja noch anpassen.
