### ISSUE TITLE
Seqeuenzdiagramm: Spiel State update

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/Meilensteine#12]

**Comment by csacro** [comment]
Ich habe das jetzt mal als Sequenzdiagramm für einen Zuschauer gemacht, weil ansonsten wäre das nach meiner Interpretation in etwa das gleiche wie bei "Aktion durchgeführen" geworden.
Passt das oder habe ich die Überschrift falsch verstanden?

**Comment by ottojo** [comment]
Ist das fertig? Wenn ja, bitte issue schließen. Looks good to me!
