### ISSUE TITLE
Zustandsdiagramm: Spiel

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/Meilensteine#15]

**Comment by Marco5de** [comment]
Ich würde sage, dass hierzu auch die Wahlphase gehört. Für diese würde sich allerdings eher ein Sequenzdiagramm anbieten.

**Comment by Marco5de** [comment]
@csacro würdest du mal noch drüber schauen ob das so passt?
Die Label Positionen sind nicht so wirklich toll, die kann man gerne noch anders anordnen. Ich hab nur nichts sinnvolleres hinbekommmen.

**Comment by ottojo** [comment]
Ich schau mir das auch gerade an, bei Siegbedingung und "Zug beendet" fehlen irgendwie pfeile, soll das so?

**Comment by ottojo** [comment]
![Bildschirmfoto_2019-12-20_10-24-23](https://user-images.githubusercontent.com/7536298/71244491-ec5b2080-2312-11ea-8709-3000f993e805.png)
How about so?

**Comment by authaldo** [comment]
Der Startpunkt sollte zur Berechnung der AP / BP führen. Im aktuellen Entwurf würde der erste Spieler mit seinem Zug starten ohne die entsprechenden Punkte berechnet zu haben

**Comment by csacro** [comment]
Man könnte noch NPC als "dritten Spieler" hinzufügen. Schließlich müssen die NPCs auch bewegt werden. Evtl. ist nächster Charakter sinnvoller, da ja nicht Spieler um Spieler, sondern Charakter um Charakter gezogen wird.
