### ISSUE TITLE
Zustandsdiagramm: Server

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/Meilensteine#16]

**Comment by ottojo** [comment]
Habe da mal ein bisschen angefangen, weiß aber nicht so recht was da rein soll...

**Comment by authaldo** [comment]
Was wir bisher noch gar nicht modelliert haben sind eventuelle Timeouts auf der Netzwerkseite. Die könnte man eventuell da und im Zustandsdiagramm des UserClients ergänzen, aber ich glaube nicht dass wir da vor Sonntag eine Spezifikation für bekommen.
Was meint ihr dazu?

**Comment by authaldo** [comment]
Ich hab das ganze mal erweitert, aus meiner Sicht fehlt jetzt nur noch eine Verbindung von Spiel zu Lobby wenn das Spielende erreicht wurde. Da muss ich mal noch schauen wie man die platztechnisch am günstigsten unterbringt.
@SoPra-Team-17/seal-team-6 Irgendwelche Einwände / Kommentare?

**Comment by authaldo** [comment]
Ich hab leider keine Möglichkeit gefunden das Label der Transition so zu platzieren, dass es nicht irgendwoanders drüber liegt.

**Comment by ottojo** [comment]
Finde ich gut! Das issue wäre dann fertig oder?

**Comment by authaldo** [comment]
Von meiner Seite aus auf jeden Fall, da keine weiteren Einwände mehr kamen würde ich das jetzt dann einfach so belassen.
