### ISSUE TITLE
Zustandsdiagramm: KI-Client

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/Meilensteine#17]

**Comment by authaldo** [comment]
@SoPra-Team-17/seal-team-6 Inwiefern erachtet ihr ein Zustandsdiagramm hier für sinnvoll? Wie die KI intern aufgebaut wird, ist in nächster Zeit ja noch nicht sicher, da wird sicher auch viel über ausprobieren laufen. Als Zustände gibt es da ja vor allem das Warten auf die Eingabe des Gegners und die Suche nach einem Zug.
