### ISSUE TITLE
Frage zum Fachwissen Eintrag Zuschauer

### ISSUE THREAD

**Issue by LukasBleile** [SoPra-Team-17/Meilensteine#19]
Hallo,
Dominik T. und ich haben uns über den Eintrag unterhalten und überlegt, ob die Spieler das gesamte Spielfeld einsehen können oder nicht? Gibt es eine Art 'Nebel des Krieges' und haben die Charaktere einen Sichtradius, der diesen lüftet und gibt es dann auch Erinnerungsspuren der Charaktere an statische Objekte des Spielfelds? Oder bezieht sich die Sichtlinie bei Gadgets nur auf die Postion der Charaktere und der Benutzerspieler sieht immer das gesamte Spielfeld inklusive aller Charakter-Bewegungen?

**Comment by ottojo** [comment]
Würde ich entscheiden, wenn wir die Netzwerk spec haben. Wenn wir die Daten vom Server bekommen, dann würde ich sie auch anzeigen (also nicht vom Fog Of War verstecken), wenn das so soll dann sollte der Server Aktionen nicht senden die der Client nicht kennen darf

**Comment by ottojo** [comment]
@SoPra-Team-17/seal-team-6 gibt es hier ein (vorläufige) Entscheidung?

**Comment by csacro** [comment]
Im Moment sollte das ja eigentlich noch keine Rolle spielen. Aber halte es auch für sinnvoll, wenn der Server dem Client nur die Daten zur Verfügung stellt, die auch er sehen kann/soll. Ansonsten kann man ja wirklich easy einen Cheat-Client machen ;-)

**Comment by ottojo** [comment]
Dann schließe ich daraus mal: Der Server schickt nur Daten, die im Sichtfeld mindestens eines Agentens der eigenen Fraktion liegen, also können wir auch nur die anzeigen -> Wir haben einen "Fog Of War"
