### ISSUE TITLE
Fachwissen

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/Meilensteine#2]
Hier bitte Begriffe fürs Glossar sammeln:

**Comment by Marco5de** [comment]
* Docker-Container
* Continous Integration
* Pull-Request/mergen
* unit-tests / monkey testing

**Comment by csacro** [comment]
- einzelne Akteure (siehe Pflichtenheft)
- Bei mir besteht eine Spielpartie aus Partie-Vorbereitung (Wahlphase und Ausrüstungsphase) und Spiel (alles nach der Partie-Vorbereitung bis Ende der Partie)

@ottojo @Marco5de @authaldo @LukasBleile : konsistente Bennenung

**Comment by csacro** [comment]
- Fraktion
- Zug
- Runde
- zu Partieconfig: Cocktail-HP, Gift-Cocktail-Schaden, ...-Wahrscheinlichkeit ?
- Angriff ?
- Zufall/zufällig ?

**Comment by ottojo** [comment]
* balancing: Anpassen der Spielparameter für Chancengleichheit für beide Spieler
* websockets
* JSON
* Szenario
* Partie
* Charakter

**Comment by LukasBleile** [comment]
Geheimnis
für die Liste mit Werten:
Tresor-Spick-Reichweite
NPC-Tresor-Kombination-Wahrscheinlichkeit
IPs-pro-Geheimnis-Wert
