### ISSUE TITLE
Sequenzdiagramm: Lobby

### ISSUE THREAD

**Issue by csacro** [SoPra-Team-17/Meilensteine#20]

**Comment by ottojo** [comment]
Kurze Frage hierzu: Bei "Betreten einer Lobby" (Sequenzdiagramm), warum macht da die KI kein "joinLobby"?

**Comment by csacro** [comment]
Weild die KI quasi gejoint wird. Mache das gleich mal anschaulicher

**Comment by ottojo** [comment]
:+1:
