### ISSUE TITLE
GUI mockups

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/Meilensteine#25]

**Comment by ottojo** [comment]
https://app.moqups.com/cChpjvXmNa/view

**Comment by dominikhoie** [comment]
https://app.moqups.com/DjpSJIyOCB/view/page/a97c0a37d    Lobby-Dialog

**Comment by dominikhoie** [comment]
https://app.moqups.com/DjpSJIyOCB/view/page/a97c0a37d Mockups für die Schnittstellenbeschreibung des KI-Clients.

https://app.moqups.com/DjpSJIyOCB/view/page/a340b9775 Mockups für die Schnittstellenbeschreibung des Editors (noch nicht vollständig).

**Comment by LukasBleile** [comment]
Wir können keine Objekte mehr zu unserem Projekt in Moqups hinzufügen, wegen der Paywall und wir haben auch keine Möglichkeit gefunden, die bisherigen Resultate in Moqups in irgendeinerweise zu exportieren um mit einem anderen Instrument daran weiterzuarbeiten. Wir werden also weiter mit Adobe XD machen, da dies in den Windowspools der SGI installiert ist.

**Comment by authaldo** [comment]
Ich hab mal noch mit dem MainMenu des Clients angefangen, aber nachdem das Exportieren bei Moqup problematisch ist, wäre es da vielleicht echt sinnvoll auf etwas anderes umzusteigen.

https://app.moqups.com/PB9EPcvCk7/view

**Comment by LukasBleile** [comment]
Adobe XD ist in den Windowspools der SGi virtualisiert mit sehr geringer Auflösung, also auch nicht wirklich gut benutzbar. Weiß jemand anderes eine gute Alternative?

**Comment by dominikhoie** [comment]
Also Lukas uns ich benutzen jetzt Pencil Project um die Mockups zu erstellen, das ist kostenlos und sieht bisher ganz gut aus. pencil.evolus.vn

**Comment by ottojo** [comment]
Das ist fertig, oder?

**Comment by dominikhoie** [comment]
Ich mache grad noch ein paar Änderungen, aber ja ist so gut wie fertig.

**Comment by dominikhoie** [comment]
Jetzt fehlt noch der Charakter-Editor, die Wahlphase und die Ausrüstungsphase als Mockup.

**Comment by ottojo** [comment]
Hab die mal gemacht
