### ISSUE TITLE
Entwicklungsvorgaben schreiben

### ISSUE THREAD

**Issue by csacro** [SoPra-Team-17/Meilensteine#30]

**Comment by LukasBleile** [comment]
Feedback erwünscht.

**Comment by Marco5de** [comment]
Ich hab mal noch einige Sachen geändert.
Sollte eigentlich so passen, aber wäre schön wenn nochmal jemand drüber schaut.

**Comment by ottojo** [comment]
Sieht für mich gut aus so. Angesichts der Zeit und dem nicht-vorhandensein weiteren Feedbacks schließe ich das mal.
