### ISSUE TITLE
Sequenzdiagramm für die Kontrollnachrichten

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/Meilensteine#33]
Anfertigen eines Sequenzdiagrams für den Standard. Vorgehen sollte aus Spiel.md hervorgehen

**Comment by Marco5de** [comment]
Nochmal kurz bisschen ausführlicher.
Wir haben heute für den Standard den Großteil der Nachrichten mal spezifiziert. Der bisher erstellte Standard ist in Standard/spiel.md.
Das Sequenzdiagramm soll den Abschnitt Kontrollnachrichten beinhalten. Sinnvoll wäre ein Ablauf wenn ein Spieler das Spiel verlässt und eines in dem das Spiel pausiert wird.

**Comment by LukasBleile** [comment]
Im Lastenheft steht die verbindliche Anforderung : "Falls ein mitspielender Client eine Pausierung der Partie wünscht, unterbricht der Server diese, bis irgendeiner der Mitspieler anzeigt, dass er weiterspielen möchte."

Wäre es nicht sinnvoller, wenn nur der Client, der die Pause gewünscht hat, die Möglichkeit hat, sie wieder aufzuheben?

**Comment by Marco5de** [comment]
Jaa wäre es
Stand im lastenheft aber anders

**Comment by LukasBleile** [comment]
Also wir machen es wie es im Lastenheft steht?

**Comment by Marco5de** [comment]
Ja genau.
Ausgemacht war eben, dass der Standard erstmal so gemacht wird, wie er im Lastenheft steht. Wenn der erste Stand dann mal vorhanden ist, kann jederzeit eine Pullrequest erstellt werden.
Kann also gut sein, dass sich das irgendwann mal noch ändert

Ist das ansonsten soweit done?

**Comment by dominikhoie** [comment]
Wir haben die Kontrollnachrichten auf zwei Sequenzdiagramme aufgeteilt, das eine ist für die Pausierungsnachrichten (das ist bereits gepusht und fertig), und das andere wäre für die Verlassensnachrichten (das fehlt noch).

**Comment by Marco5de** [comment]
@dominikhoie @LukasBleile , habt ihr mit dem Sequenzdiagramm für Verlassensnachrichten schon angefangen? 
Theoretisch sollte das in ner guten Stunde fertig sein, aber wenn ihr da noch nichts habt, ist das auch nicht so schlimm. Bis spätestens zum nächsten Netzwerkstandard treffen sollte es halt fertig sein

**Comment by dominikhoie** [comment]
Ich habe jetzt mal einen Entwurf hochgeladen. In Spiel.md ist die Rede von dem Fall, dass ein Spieler das Spiel verlässt. Das habe ich in dem Sequenzdiagramm abgebildet. Ein Zuschauer kann das Spiel ja auch verlassen, aber ich denke dann bekommen die anderen Clients keine Benachrichtigung. Dieser Fall ist jetzt noch nicht enthalten, ich habe im Lastenheft aber auch nichts dazu gefunden, wie Zuschauer ein Spiel verlassen, da sie ja nicht am Spiel teilnehmen, sondern sich nur im Zuschauermodus befinden.

Bei beiden .tex-Dateien entsteht beim Kompilieren eine leere Seite am Anfang und ich weiß nicht wieso. Und evtl. kann man auch beide Diagramme in eine Datei packen, dann wird es halt länger als eine DIN A4-Seite. Und falls jemand weiß, wie man den Abstand innerhalb der alt-Blöcke verringern kann, kann er sich gerne melden. Da ist relativ viel Whitespace, den ich nicht wegbekomme, ohne dass sich alles andere verschiebt.

**Comment by Marco5de** [comment]
Evtl. sollte sich der Zuschauer zumindest beim Server abmelden. 
Die anderen Spieler brauchen die Info eigentlich nicht unbedingt, außer man will im Spiel auch Zuschauen anzeigen aber das klingt sehr nach einem Optional.

Das ist egal, am Ende muss da sowieso jemand Dokumentenpflege betreiben und das alles zusammen packen.
