### ISSUE TITLE
Architekturentwurf

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/Meilensteine#36]
Erstes Issue. Sollte noch feiner aufgeteilt werden auf die einzelnen Komponenten.

**Comment by csacro** [comment]
Ich hab mir mal bisschen was überlegt. FAs hab ich noch keine zu den einzelnen Komponenten dazugeschrieben.
@SoPra-Team-17/seal-team-6  Feedback erwünscht und es kann gerne jeder Änderungen dran vornehmen
