### ISSUE TITLE
Netzwerkstandard überarbeiten

### ISSUE THREAD

**Issue by Marco5de** [SoPra-Team-17/Meilensteine#37]
> Die Kleinigkeiten, die während der Sitzung aufgefallen sind, habe ich bereits angepasst. Was noch gemacht werden muss, ist:

> - Das GadgetEnum muss definiert werden.

>- Es muss ein Datenmodell zu allen Gadgets erstellt werden. D.h., wir müssen für alle Gadgets geeignete Unterklassen, die von Gadget erben, angeben. Nur die Attribute, die das Gadget braucht, sollen enthalten sein.
>- Es muss ein Datenmodell zu allen Aktionsarten erstellt werden. D.h., wir müssen für alle Aktionsarten (Spionage, Tresorknacken, GadgetAktion) eine spezialisierte Unterklasse angeben, die von Action erbt. Nur die Attribute, die die jeweilige Aktion braucht, sollen enthalten sein.

>Ich habe gestern paar Stunden zur Dokumentenpflege aufgebracht. Deswegen würde ich die Aufgaben euch zuschieben. Teilt es unter euch auf
Was muss man aus eurer Sicht noch machen?

von Jo, ich hab mal zugesagt, dass wir uns um das Datenmodell zu allen Aktionsarten kümmern
Wäre schön, wenn sich da jemand Gedanken machen könnte. Es eilt zwar noch nicht, aber wäre schön was das zügig erledigt wäre.

**Comment by Marco5de** [comment]
Ich hatte vergessen, das aktuelle Standarddokument hochzuladen. Ist jetzt mit 7eebd8d2c60213b0ff7ed5a3cbb8dc430995d1f5 erledigt.
Wäre cool, wenn sich jemand um das Issue kümmern könnte.

**Comment by LukasBleile** [comment]
Im Abschnitt Operation unter der Deklaration der abstrakten Klasse Operation werden drei Attribute beschrieben. Zwei davon sind Attribute der abstrakten Klasse Operation, das dritte ist ein Attribut der Unterklasse Action. Kann es sein, dass die abstrakte Klasse Operation auch das dritte Attribut hat, da auch eine Bewegung fehlschlagen kann, z.B. wenn ein Benutzer versucht, den Charakter in eine Wand laufen zu lassen? Oder ist der Satz dorf fehl am Platz?

**Comment by LukasBleile** [comment]
Unter der Deklaration der Klasse Action steht im ersten Punkt, dass es unter Anderem eine Cocktail-Aktion sein kann, wenn das Attribut gadgetId den Wert null hat. Weiter unten steht dann im TODO als Erinnerung, dass Cocktails Gadgets seien. Ich kann nicht nachvollziehen, woher die Aussage kommen soll, dass Cocktails Gadgets sind. Bitte erklären?

**Comment by LukasBleile** [comment]
Die beiden Charakter-Eigenschaften 'Bang and Burn' und 'Observation' geben einem Charakter je eine weitere Aktion als Möglichkeit, einen Aktionspunkt auszuführen. Wie können diese Aktionstypen in der Klasse des Netzwerkstandards abgebildet werden?

**Comment by LukasBleile** [comment]
Wir haben jetzt ein Datenmodell für die Tresor-Aktion gemacht. Bei einem der Attribute bin ich mir nicht sicher, ob es benötigt wird. Ich bin mir auch nicht sicher, ob es nötig wäre, als Attribut zu definieren, das angibt, ob die Fraktion des ausführenden Charakters die Kombination zu dem ausgewählten Tresor überhaupt kennt.

**Comment by LukasBleile** [comment]
Wir haben auch ein Datenmodell für Roulette-Aktion und Gadget-Aktion gemacht, aber uns ist kein einziges Attribut eingefallen, welches die Klasse für Gadget-Aktion benötigen würde, wenn in der Aktion sowieso schon die Gadget-ID übergeben wird.

**Comment by Marco5de** [comment]
> Im Abschnitt Operation unter der Deklaration der abstrakten Klasse Operation werden drei Attribute beschrieben. Zwei davon sind Attribute der abstrakten Klasse Operation, das dritte ist ein Attribut der Unterklasse Action. Kann es sein, dass die abstrakte Klasse Operation auch das dritte Attribut hat, da auch eine Bewegung fehlschlagen kann, z.B. wenn ein Benutzer versucht, den Charakter in eine Wand laufen zu lassen? Oder ist der Satz dorf fehl am Platz?

Das ist nicht sinnvoll. Eine Bewegungsaktion, wenn valide, kann nicht fehlschlagen. Wenn ein nicht valider Zug beim Server ankommt, wird der Client ohnehin gekickt. Das heißt, alle Züge sollten vorher bereits beim Client validiert werden!

**Comment by Marco5de** [comment]
> Unter der Deklaration der Klasse Action steht im ersten Punkt, dass es unter Anderem eine Cocktail-Aktion sein kann, wenn das Attribut gadgetId den Wert null hat. Weiter unten steht dann im TODO als Erinnerung, dass Cocktails Gadgets seien. Ich kann nicht nachvollziehen, woher die Aussage kommen soll, dass Cocktails Gadgets sind. Bitte erklären?

Es wurde festgelegt, dass der Cocktail ab jetzt ein Cocktail ist. Grund dafür ist, dass der Cocktail zuvor unabhängig war und dann dafür eine eigene Nachricht oder ein eigenes Feld hätte erstellt werden müssen, Der Cocktail wird jetzt einfach als aufnehmbares Gadget beschrieben!
Ein Cocktail sollte dann aber auch eine Gadget ID haben

**Comment by Marco5de** [comment]
> Die beiden Charakter-Eigenschaften 'Bang and Burn' und 'Observation' geben einem Charakter je eine weitere Aktion als Möglichkeit, einen Aktionspunkt auszuführen. Wie können diese Aktionstypen in der Klasse des Netzwerkstandards abgebildet werden?

Die Gadgets sind fest, d.h. es kommen keine Weiteren dazu und daher muss in der Netzwerknachricht nicht spezifiziert sein, welche Auswirkung das Gadget auf AP/BP hat. Das kann in der Spiellogik des Servers hinterlegt werden.

**Comment by Marco5de** [comment]
Im Allgemeinen gibt es nicht zu allen Gadgets sinnvolle Attribute. Was da aber bspw. dazugehört ist die Range des Gadgets, Schaden, Usages.
In der Klassen sind also Werte enthalten, welche relativ einfach geändert werden können. Dazu gehört bspw. nicht die Ändernungen der HP/BP etc. welche eine Gadget-Aktion bewirkt.
