### ISSUE TITLE
Aufgabe 2: Abläufe im System

### ISSUE THREAD

**Issue by ottojo** [SoPra-Team-17/Meilensteine#9]
## Seqeuenzdiagramme
- [ ] Verbindungsinitialisierung, Spielstart: @ottojo 
- [ ] Aktion durchführen und weiterleiten: @ottojo
- [ ] Spiel State update (?)
- [ ] Spielende, Verbindungsabbau

## Zustandsdiagramme
- [ ] BenutzerClient (Spiel: Nur Aktionen des Benutzers)
- [ ] Spiel: @Marco5de 
- [ ] Server
- [ ] KI-Client

**Comment by Marco5de** [comment]
ich würde mir das Zustandsdiagram für den Client anschauen, also alles was im Spiel passiert

**Comment by ottojo** [comment]
(Umgewandelt in einzelne Issues)
